sudo: requiered
language: java
services:
   - docker
before_install: cd hello-namespaces
script:
  - ./mvnw package -Pnative -Dnative-image.docker-build=true
after_script:
  - docker build -t tonyproum/hello-namespaces -f src/main/docker/Dockerfile.native .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push tonyproum/hello-namespaces;
      fi
